channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=24.0
- pip:
  - mlflow==2.14.2
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.1
  - pandas==2.2.2
  - pyyaml==6.0.1
  - torch==2.3.1
name: mlflow-env
